### ISSUE TITLE
Why can't I assign a variable more than once before using it?

### ISSUE THREAD

**Issue by yisiliu** [RealTimeWeb/blockpy#28]
I don't really get the logic behind this error: "One of the times that you gave a a value was incorrect."

**Comment by acbart** [comment]
I'm afraid this Github is not meant for programming advice. If you have questions about specific programming questions you are working on, then you can post on a service like StackOverflow.

As to the design decision of why we consider that an error, it's because you should never redefine a variable before you use it.
